[openvswitch] Collect ovs threads list in ps and in procfs
sosreport/sos pull request #1967
Opened 2020-02-25 09:16 UTC by links84

Get detailed ps output of all ovs-vswitchd threads including last cpu
known to run on, priority etc from ps. Also copy 
/proc/<ovs-vswitchd thread id>/{environ,cgroup,maps,numa_maps,limits,
status} to indicate configured cpu affinity and other details.
These information are critical for troubleshooting NFVi openstack
deployments.

Fixes: #1687
Signed-off-by: Jaison Raju <jraju@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ x] Is the subject and message clear and concise?
- [ x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [x ] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [x ] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

2020-02-27 16:39 UTC, TurboTurtle requested changes

2020-02-27 16:39 UTC, TurboTurtle commented on sos/plugins/openvswitch.py
> +        ps_sched_opts += "flags,comm"
I think this is better served going into the `process` plugin.

We do 5 total `ps` calls at the moment, I'd say it's time for a review of those, especially with this new addition, to see where we can merge or drop certain collections. 

That review wouldn't be on you here. In any event however, I don't think adding these calls to individual plugins is the right approach.

2020-02-27 16:39 UTC, TurboTurtle commented on sos/plugins/openvswitch.py
> +                                % (pid, pf) for pf in proc_files])
Please use sos-style here, E.G.

```python
self.add_copy_spec([
    "/proc/%s/task/*/%s" % (pid, pf) for pf in proc_files
])
```

2024-11-21 20:29 UTC, arif-ali commented
@links84 it's been a while since this PR was touched, any thoughts on updating and merging this?

2026-07-13 17:16 UTC, TurboTurtle commented
Closing as abandoned.

2026-07-13 17:16 UTC, closed without merging