[kdump] Collect the list of files compressed by squashfs
sosreport/sos pull request #2283
Opened 2020-10-27 06:24 UTC by s-morishima

Initramfs for kdump has "squash/root.img" compressed by squashfs.
It includes files needed by kdump kernel to boot. The list of them
is collected.

Signed-off-by: MORISHIMA shigeki <s.morishima@fujitsu.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [ ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ ] Is the subject and message clear and concise?
- [ ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [ ] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

2020-10-27 06:28 UTC, s-morishima commented
Could you please provide me with your suggestions to improve
this patch?

Unfortunately, this patch has one problem. A temporary file
remains existing after collecting this diagnostic information
due to "delete=False" specified in NamedTemporaryFile.
At the moment, collecting this diagnostic information needs
"delete=False" because the temporary file is deleted
before actually collecting this diagnostic information
if "delete=False" isn't specified. I don't think that
this problem can be solved only on this plugin.

2020-10-27 11:44 UTC, bmr-cymru requested changes
I understand what you're trying to do here but the implementation needs a re-think to fit in with `sos` plugin conventions.

2020-10-27 11:44 UTC, bmr-cymru commented on sos/report/plugins/kdump.py
> +import subprocess
Nack: do not import subprocess directly in plugin files. Use the APIs provided for this purpose by the `Plugin` class (that set the correct `Popen()` arguments and that handle all the necessary path conversions and logging).

2020-10-27 11:44 UTC, bmr-cymru commented on sos/report/plugins/kdump.py
> +                p = subprocess.Popen(['lsinitrd', '-f', 'squash/root.img', initramfs_img], stdout=tempfp)
You can't leave temporary files lying around after an sos run. This either has to be done using a pipe between the `lsinitrd -f` and `unsquashfs -ll` commands, or by using temporary paths that are contained in the `sos` working directory (and so are cleaned up during exit handling).

2020-10-27 12:14 UTC, bmr-cymru commented
> Unfortunately, this patch has one problem. A temporary file
> remains existing after collecting this diagnostic information
> due to "delete=False" specified in NamedTemporaryFile.
> At the moment, collecting this diagnostic information needs
> "delete=False" because the temporary file is deleted
> before actually collecting this diagnostic information
> if "delete=False" isn't specified. I don't think that
> this problem can be solved only on this plugin.

Unfortunately `unsquashfs` does not seem to support reading the compressed file system data from standard input: this would be the ideal way for this to work (it might be possible with `squashfs-tools-ng`, but that is not available in many distributions).

Without this the best option is to place the tmpfile.NamedTemporaryFile into the sos working directory by passing the `dir=` keyword argument. This can be done using existing sos and plugin interfaces but it's fine to suggest improvements to the APIs if they make this case easier to handle.

2020-10-29 06:07 UTC, s-morishima commented
Thank you for your suggestion.

> This can be done using existing sos and plugin interfaces
> but it's fine to suggest improvements to the APIs if they make this case easier to handle.

I'll consider both of them. First, I'll consider to add new APIs to somewhere (e.g. Plugin class)
to handle this problem more properly.

> Nack: do not import subprocess directly in plugin files. Use the APIs provided for this purpose 
> by the Plugin class (that set the correct Popen() arguments and that handle all the necessary 
> path conversions and logging).

I see. I'll address this comment as well by using the APIs of the Plugin class instead.

2021-02-04 04:52 UTC, s-morishima commented
I apologize for my late response.

Recently, I found that lsinitrd command became able to list the squash content
on Fedora33. lsinitrd has already been fixed on dracut upstream, and 
my purpose also has already been achieved. 
Therefore, I will close this pull request.

Thank you for your cooperation.

2021-02-04 04:52 UTC, closed without merging