insights.py: Adding .registered file to Insights client config collection
sosreport/sos pull request #2373
Opened 2021-01-13 22:45 UTC by PaulWay

This makes it easier for users to tell if the Insights client is
registered on the target system.

Signed-off-by: Paul Wayper <paulway@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [ ] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

2021-01-13 23:48 UTC, TurboTurtle requested changes
The addition is fine, but please take a look at the [Contribution Guildeines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines) for how the commit message needs to be formatted.

Basically:
- Commit message needs a subject tag, e.g. `[insights]`.
- If this is meant to close out #2372, please include `Closes: #2372` (checkmark 5 in the PR template)
- Please include `Resolves: #2373` in the commit message as well (checkmark 6)

2021-01-14 03:10 UTC, PaulWay commented
OK, thanks @TurboTurtle - have updated the description to include those tags.  I didn't include them initially because I thought that was some kind of built-in 'close and/or resolve this issue' automation that I didn't want to invoke accidentally.

2021-01-14 14:22 UTC, TurboTurtle commented
@PaulWay actually I meant the commit message, not the github PR description.

You can do this via:

```
$ git commit --amend
< make changes >
$ git push <branch> --force

```

2021-01-25 22:11 UTC, PaulWay commented
Hi @TurboTurtle - sorry for not getting to this sooner, work was a bit busy :-)

2021-01-29 17:40 UTC, TurboTurtle approved these changes

2021-01-29 19:41 UTC, closed without merging