Georgian translation
sosreport/sos pull request #2976
Opened 2022-07-16 16:37 UTC by NorwayFun

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [ X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ X] Is the subject and message clear and concise?
- [ X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

2022-07-18 13:57 UTC, TurboTurtle approved these changes
LGTM

2022-07-18 15:21 UTC, TurboTurtle requested changes
Actually, one thing I noticed on a second pass.

@NorwayFun please add a DCO line to the commit message per the [Contribution Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines). You can do this with `git commit -s --amend`.

2022-07-23 15:35 UTC, NorwayFun commented
Is anything else needed from my side?

2022-07-23 17:10 UTC, pmoravec approved these changes

2022-07-25 14:32 UTC, TurboTurtle approved these changes

2022-07-25 14:32 UTC, merged