[policies] Add policy for OpenCloudOS
sosreport/sos pull request #3104
Opened 2023-01-06 07:17 UTC by ZoeDong

Add a basic policy for OpenCloudOS distributions. 

Signed-off-by: zoedong <zoedong@tencent.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [x] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

2023-01-06 07:35 UTC, pmoravec approved these changes

2023-01-06 07:36 UTC, pmoravec requested changes
Please fix the flake failures:

https://github.com/sosreport/sos/pull/3104/checks?check_run_id=10477268912

2023-01-06 13:54 UTC, pmoravec approved these changes

2023-01-06 15:48 UTC, TurboTurtle reviewed
Ack. Though please squash the fixup commit into the original, per the [Contribution Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

2023-01-09 02:59 UTC, ZoeDong commented
Thanks for reviewing! I have already squash the fixup~

2023-01-09 15:56 UTC, TurboTurtle approved these changes

2023-01-09 15:56 UTC, merged