[policies] Add RedFlag OS policy
sosreport/sos pull request #3276
Opened 2023-06-19 03:32 UTC by gogv

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

2023-06-19 09:22 UTC, gogv commented
snap Build From Checkout Failing after 2m — Task Summary

2023-06-19 09:31 UTC, gogv commented
I am building and publishing locally normally. What does this snap detect?

2023-06-19 14:12 UTC, arif-ali commented
@gogv Thanks for your contribution

I have verified, that I see the same issue building the snap in my local environment, this is very likely an issue with snapcraft and not with your commit. I will get back to this issue at some point.

Furthermore, could you follow the contribution guideline at [1]

1. Can you put everything in english please, so that everyone can understand the code
2. Can you add The `Signed-off-by:` line too please to your commit
3. Once everything is approved you will need to squash your commits

[1] https://github.com/sosreport/sos/wiki/Contribution-Guidelines

2023-06-19 14:46 UTC, arif-ali commented
@gogv once PR #3277 gets merged, please re-base your commits on that please

2023-06-20 06:43 UTC, arif-ali reviewed
Can you update the PR based on my comments

* You don't need to add the commits from `main` branch, but you need to rebase to main, please see [1] as an example on how to do this (But you need for the snap PR to be merged first to finalise)
* Please follow the guidelines [2], and update the `rfedflag.py` using the License Header and Copyright


[1] https://stackoverflow.com/questions/54674971/github-fetch-and-rebase-fork-on-forked-master
[2] https://github.com/sosreport/sos/wiki/Contribution-Guidelines

2023-06-20 06:43 UTC, arif-ali commented on sos/policies/distros/redflag.py
> +# 有关详细信息，请参阅源发行版中的LICENSE文件。
Can you update this based on the guidelines, and can you put this in English please

2023-06-20 06:43 UTC, arif-ali commented on sos/policies/distros/redflag.py
> +        # 如果/etc/os-release丢失，则返回False
same as above

2023-06-20 06:43 UTC, arif-ali commented on sos/policies/distros/redflag.py
> +        # 如果/etc/redflag-release丢失，则返回False
same as above

2023-06-20 06:43 UTC, arif-ali commented on sos/policies/distros/redflag.py
> +        # 检查/etc/os-release中的RedFlag
same as above

2023-06-20 12:14 UTC, pmoravec commented on sos/policies/distros/redflag.py
> +    vendor_urls = [('Distribution Website', 'http://www.redflag-os.com')]
My original point was a nitpick "can you provide rather a link to https pages, please?" but it seems the project runs (untrusted) http pages only..? (then this line would be fully OK).

2023-06-20 12:15 UTC, pmoravec commented
As @arif-ali wrote: please use English in comments and rebase your branch first (to have PR with just one commit).

2023-06-21 14:03 UTC, TurboTurtle requested changes
The policy looks ok by itself, however you'll need to rebase and squash your fixup commits - this should ideally be contributed in a single commit.

2023-06-21 14:08 UTC, TurboTurtle commented
Also, I'm a little concerned about the state of this distro.  A cursory Google search shows that places like [DistroWatch](https://distrowatch.com/table.php?distribution=redflag) has it marked as "discontinued", and several other communities have it noted that development stopped as far back as 2013, and that the commercial entity behind it went out of business in 2014.


So, before we move any further - what's the current status of the distribution, its community, and/or any commercial entity backing it?

2023-06-27 06:10 UTC, gogv commented
In 2014, it was acquired by Beijing Hongqi Software and currently mainly provides services to Bank of China.

2023-06-29 07:02 UTC, gogv commented
https://zh.wikipedia.org/wiki/%E7%B4%85%E6%97%97Linux

2023-07-03 08:22 UTC, arif-ali commented
@gogv this PR has still got 22 commits, which is not correct; and has commits that are already in the `main` branch

We should be rabasing as per my comments 2 weeks ago; as per my comment on Friday and from @TurboTurtle this PR or any PR should only have your commit (or change), and ideally 1 commit

2023-07-03 08:26 UTC, closed without merging