[grafana] conf and logs from snap added
sosreport/sos pull request #3289
Opened 2023-06-27 09:05 UTC by GairePravesh

files added:
    /var/snap/grafana/common/data/log/grafana.log*
    /var/snap/grafana/current/conf/grafana.ini

cmds added:
    snap info grafana
    grafana.grafana-cli plugins ls
    grafana.grafana-cli plugins list-remote

Closes: #3278

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [ ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ ] Is the subject and message clear and concise?
- [ ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

2023-06-27 12:44 UTC, pmoravec commented on sos/report/plugins/grafana.py
> +            )
If the only change is in filename, maybe it is easier to have:

    inifile = `"/var/snap/grafana/current/conf/grafana.ini"` if self_is_snap else "/etc/grafana/grafana.ini"
    regexp = r"((?m)^\s*(%s)\s*=\s*)(.*)" % "|".join(protect_keys)
    self.do_path_regex_sub(
        inifile,
        regexp,
        r"\1*********"
    )

2023-06-27 12:45 UTC, pmoravec commented on sos/report/plugins/grafana.py
> +            "client_secret"
+1, that helps also to non-snap instances.

2023-06-27 12:52 UTC, arif-ali reviewed
@GairePravesh Thanks for your contribution

probably nits more than anything

*  What about creating a variable called `grafana_cli`, and based if it is snap or standard, and then use that variable to do the `grafana-cli` commands. This way, if more commands are needed we add 1 line rather than duplication
* We could probably do the same with both the log path and config path, as they would be similar

i.e.

```python
if self._is_snap:
    grafana_cli = "grafana.grafana-cli"
else:
    grafana_cli = "grafana-cli"

self.add_cmd_output([
    "%s plugin ls" % grafana_cli,
    "%s plugin list remote" % grafana_cli,
    "%s -v" % grafana_cli,
])
```

2023-06-27 12:54 UTC, pmoravec commented
Generally ACK, just a though: since the "snap instance or not" call flows differ a lot, it would maybe make more sense to have `SnapPlugin` class likewise we have `RedHatPlugin` or `DebianPlugin`? Though the `Plugin` hierarchy is likely distribution-based, not package-manager-based. But maybe if some other plugins might benefit from this in future, it should be easy to add `SnapPlugin` (likewise https://github.com/sosreport/sos/blob/main/sos/policies/distros/ubuntu.py#L49)?

2023-06-27 15:03 UTC, arif-ali commented
> Generally ACK, just a though: since the "snap instance or not" call flows differ a lot, it would maybe make more sense to have `SnapPlugin` class likewise we have `RedHatPlugin` or `DebianPlugin`? Though the `Plugin` hierarchy is likely distribution-based, not package-manager-based. But maybe if some other plugins might benefit from this in future, it should be easy to add `SnapPlugin` (likewise https://github.com/sosreport/sos/blob/main/sos/policies/distros/ubuntu.py#L49)?

I do like the idea, I will have a look at this in the background, and see how that looks with refactoring a few of the other plugins that has this already, like `maas` and `lxd`

2023-06-27 23:42 UTC, TurboTurtle reviewed
> ```python
> if self._is_snap:
>     grafana_cli = "grafana.grafana-cli"
> else:
>     grafana_cli = "grafana-cli"
> 
> self.add_cmd_output([
>     "%s plugin ls" % grafana_cli,
>     "%s plugin list remote" % grafana_cli,
>     "%s -v" % grafana_cli,
> ])
> ```

This, but please note that f-strings are preferred per the contributions guidelines.

The intent of the changes looks good, just simplifying the flow as suggested above would be my 2 cents.

As far as a `SnapPlugin` goes, I'm not sure how well we'd be able to have that in tandem with distro-based enablement without things getting real fragile.

Perhaps instead we could add a helper method like `self.is_pkg_snap('$pkg')`  (and accompanying `is_pkg_rpm()`, `is_pkg_deb()` etc...) to better support these checks within the current scope of enablement desgns?

2023-08-16 08:58 UTC, arif-ali requested changes

2023-08-16 14:02 UTC, TurboTurtle commented on sos/report/plugins/grafana.py
> +            "/etc/sysconfig/grafana-server" if not self._is_snap else None
`add_copy_spec()` also handles non-existing paths gracefully, so we can just have it listed here and it will be ignored for snap installations.

2023-08-16 14:02 UTC, TurboTurtle commented on sos/report/plugins/grafana.py
> +            'grafana-server -v' if not self._is_snap else None
Likewise we don't need to gate the `snap info` command, we can just tuck an `add_cmd_output()` under the conditional on line 30.

2023-11-09 10:07 UTC, closed without merging

2023-11-09 10:07 UTC, arif-ali commented
This is being closed in favour of #3410, Pravesh will not longer be contributing