[lustre] Collect most params
sosreport/sos pull request #3424
Opened 2023-11-27 18:22 UTC by utopiabound

Collect almost all params, except those explicitly excluded.
Those excluded are known to be less useful debugging, and/or known to be very large.

Some params are still split out to help limit size.

Some very large (but possibly useful) param are relegated to `--all-logs`

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

2023-11-27 19:57 UTC, jcastill requested changes

2023-11-28 15:54 UTC, TurboTurtle approved these changes
LGTM. I restarted the CI jobs.

2023-11-30 17:25 UTC, jcastill approved these changes

2023-12-08 14:43 UTC, TurboTurtle approved these changes

2023-12-26 19:58 UTC, merged