[plugin_ceph] adding the healthcheck history for more detailed view on alerts firing
sosreport/sos pull request #3579
Opened 2024-03-21 18:24 UTC by michaelalang

adding the `ceph healthcheck history ls` command will provide a detailed view of Healthchecks failing and or active

``` 
# ceph healthcheck history ls 
Healthcheck Name          First Seen (UTC)      Last seen (UTC)       Count  Active
CEPHADM_APPLY_SPEC_FAIL   2023/05/19 17:00:38   2024/03/21 14:52:58     637    No  
CEPHADM_DAEMON_PLACE_FAIL  2023/05/19 07:24:53   2024/01/12 19:18:23      66    No  
CEPHADM_FAILED_DAEMON     2023/05/19 07:04:08   2024/02/09 19:22:48      34    No  
CEPHADM_HOST_CHECK_FAILED  2023/05/19 06:19:06   2024/03/21 15:45:10     190    No  
CEPHADM_PAUSED            2023/05/19 16:42:23   2023/07/27 17:54:13       5    No  
CEPHADM_REFRESH_FAILED    2023/05/19 07:24:38   2024/03/20 07:48:15     971    No  
[..output omitted..]
```
---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [ ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [ ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

2024-03-21 19:25 UTC, arif-ali requested changes
Can you squash your commits into 1 please

2024-03-21 19:34 UTC, michaelalang commented
@arif-ali sorry I am a git dummy ... 
if I drop my initial branch it will close the PR if I am not wrong ... any hint how to achieve the requested squashing ?

2024-03-21 19:58 UTC, michaelalang commented
okay I hope I did it right squashing the commits into one

2024-03-21 22:43 UTC, TurboTurtle reviewed
Code change LGTM.

Please see our [Contribution Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines) however for the commit message. We use a `[tag] Short Description` format, e.g. `[ceph] Add healthcheck history collection` (and then using the commit body for more details). I know this seems trivial, but it honestly helps a ton when searching through the git history.

You can fix this up and force push, like so:

`git commit --amend`
<make changes to the commit header and body message>
`git push origin <your_branch> --force`

2024-03-22 00:58 UTC, nobuto-m commented
I thought I added the healthcheck history before:
https://github.com/sosreport/sos/pull/3512
(it's in the mgr module)

2024-03-22 05:20 UTC, michaelalang commented
@nobuto-m hmm yes seems that my request is a duplicated. I was told that we would benefit a lot adding that command and even in latest RHEL 9.3 it's not integetrated ... 
Please close the request if everyone agrees it's a duplicate and I will try to get your commit cherry picked downstream accordingly.

thanks for pointing it out <3
and sorry guys for not checking it on my own upfront

2024-03-22 10:05 UTC, closed without merging

2024-03-22 10:05 UTC, michaelalang commented
duplicate closing check PR https://github.com/sosreport/sos/pull/3512 instead