[foreman] [foreman_proxy] Add ALL_PROXY and NO_PROXY to collected env_vars
sosreport/sos pull request #3792
Opened 2024-09-26 11:10 UTC by pafernanr

Add ALL_PROXY and NO_PROXY to collected env_vars

Resolves: #3788

**Signed-off-by: Pablo Fernández Rodríguez <pafernan@redhat.com>**
---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [ x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ x] Is the subject and message clear and concise?
- [ x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ x] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
- [x ] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to-prevent-collecting-passwords)?

2024-09-26 11:28 UTC, jcastill requested changes

2024-09-26 11:28 UTC, jcastill commented on sos/report/plugins/foreman.py
> +            'ALL_PROXY'
little thing here, but can you add a comma at the end?

2024-09-26 11:28 UTC, jcastill commented on sos/report/plugins/foreman_proxy.py
> +            'ALL_PROXY'
same here, comma at the end of 'ALL_PROXY'

2024-09-26 12:24 UTC, jcastill commented
@pafernanr looks good to me, but can you squash them all together?

2024-09-26 14:33 UTC, pafernanr commented
@jcastill thanks for your tips.

2024-09-27 11:14 UTC, arif-ali commented
@pafernanr can you squash the commits, so that we only see one commit please. That's what @jcastill was suggesting

2024-09-27 20:25 UTC, pmoravec approved these changes
ACK to the change itself.

Just the commit contains also one commit from main :-o and manual merge must be done.

2024-09-28 12:37 UTC, closed without merging