[policies] Fix bug in distro identification
sosreport/sos pull request #3870
Opened 2024-12-11 07:21 UTC by metalefty

Fixes a bug in #3764.

A bug in the distro-identifying logic caused incorrect identification of the distro as CentOS, Fedora, or RHEL under the following conditions:

1. Distro inherits RedHatPolicy
2. Distro has either of /etc/{centos,fedora,redhat}-release
3. Policy file appears earlier than redhat.py in dictionary order

The issue occurs because the distro-identifying logic relies on the existence of the above os_release_file without examining its contents, more than checking NAME or ID in the /etc/os-release file. As a result, once /etc/{centos,fedora,redhat}-release is found, the contents of /etc/os-release are never checked, leading to distro misidentification.

At least AlmaLinux is affected by this bug.

---

## Steps to reproduce

### AlmaLinux 9

#### On the container host
```shell
$ git clone https://github.com/sosreport/sos
$ podman run -it --rm -v .//sos:/sos quay.io/almalinuxorg/almalinux:9 /bin/bash
```

#### Inside the container
```
# ls -l /etc/*-release
-rw-r--r--. 1 root root 36 Nov 12 09:29 /etc/almalinux-release
lrwxrwxrwx. 1 root root 21 Nov 12 09:29 /etc/os-release -> ../usr/lib/os-release
lrwxrwxrwx. 1 root root 17 Nov 12 09:29 /etc/redhat-release -> almalinux-release
lrwxrwxrwx. 1 root root 17 Nov 12 09:29 /etc/system-release -> almalinux-release
# cat /etc/almalinux-release
AlmaLinux release 9.5 (Teal Serval)
# dnf install -y python3-setuptools
# cd sos
# python3 -m venv env && source env/bin/activate
# pip install -r requirements.txt
# bin/sos rep

(snip)

sos report (version 4.8.1)

(snip)

This command will collect diagnostic and configuration information from
this Red Hat Enterprise Linux system and installed applications.

An archive containing the collected information will be generated in
/var/tmp/sos.khtjjzfz and may be provided to a Red Hat support
representative.

Any information provided to Red Hat will be treated in accordance with
the published support policies at:

        Distribution Website : https://www.redhat.com/
        Commercial Support   : https://access.redhat.com/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.

Press ENTER to continue, or CTRL-C to quit.
```

### AlmaLinux 8
#### On the container host
```shell
$ git clone https://github.com/sosreport/sos
$ podman run -it --rm -v .//sos:/sos quay.io/almalinuxorg/almalinux:8 /bin/bash
```

#### Inside the container
```
# ls -l /etc/*-release
-rw-r--r--. 1 root root 42 May 22  2024 /etc/almalinux-release
lrwxrwxrwx. 1 root root 17 May 22  2024 /etc/centos-release -> almalinux-release
lrwxrwxrwx. 1 root root 21 May 22  2024 /etc/os-release -> ../usr/lib/os-release
lrwxrwxrwx. 1 root root 17 May 22  2024 /etc/redhat-release -> almalinux-release
lrwxrwxrwx. 1 root root 17 May 22  2024 /etc/system-release -> almalinux-release
# cat /etc/almalinux-release
AlmaLinux release 8.10 (Cerulean Leopard)
# dnf install -y python3.11 python3.11-setuptools
# cd sos
# python3.11 -m venv env && source env/bin/activate
# pip3.11 install -r requirements.txt
# bin/sos rep

WARNING: Failed to load 'magic' module version >= 0.4.20 which sos aims
to use for detecting binary files. A less effective method will be used.
It is recommended to install proper python3-magic package with the
module.

(snip)

sos report (version 4.8.1)

(snip)

This command will collect diagnostic and configuration information from
this CentOS Linux system and installed applications.

An archive containing the collected information will be generated in
/var/tmp/sos.az9ho1x4 and may be provided to a CentOS support
representative.

Any information provided to CentOS will be treated in accordance with
the published support policies at:

        Community Website : https://www.centos.org/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.

Press ENTER to continue, or CTRL-C to quit.
```

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [x] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
- [x] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to-prevent-collecting-passwords)?

2024-12-11 07:33 UTC, jcastill approved these changes
lgtm

2024-12-11 07:54 UTC, metalefty commented
I have just added a small change to the code comment, no logic change.

2024-12-11 08:33 UTC, arif-ali approved these changes
lgtm, can you squash your commits, as we prefer 1 commit per PR

2024-12-11 08:37 UTC, metalefty commented
@arif-ali squashed and force-pushed.

2024-12-11 09:38 UTC, metalefty commented on sos/policies/distros/__init__.py
> +        if os.path.isfile(cls.os_release_file):
Ah, my code contains unreachable statement as CodeQL pointed out.

This looks more appropriate. Let me check again tomorrow.
```python
if not os.path.isfile(cls.os_release_file):
    return False
with open(OS_RELEASE, "r", encoding='utf-8') as f:
    return _check_release(f.read())

2024-12-11 10:45 UTC, pmoravec commented on sos/policies/distros/__init__.py
> +        if os.path.isfile(cls.os_release_file):
.. and I was blind I havent detected this :(

2024-12-11 16:12 UTC, TurboTurtle reviewed
I think there's a better solution here. The file name check is meant to be the primary way a policy identifies itself, but what we actually have here is a race condition between the loading of the RHEL policy class vs the Alma class and the existence of more than one release file.

That said, I think the better solution here is to check against the absolute destination of the provided `os_release_file` in a policy, in the case that distribution drops symlinks for other well known paths, like what you've shown in your case.

2024-12-12 05:26 UTC, metalefty commented
> I think the better solution here is to check against the absolute destination of the provided os_release_file in a policy, in the case that distribution drops symlinks for other well known paths, like what you've shown in your case.

> as at least for Fedora we'd need to change it from `/etc/fedora-release` to `/usr/lib/fedora-release`.

@TurboTurtle Thanks for the feedback. I managed to add check for symlink destination name with taking care of `/usr/lib/fedora-release`. See the added commit. 

Here is a snippet of the essence of the change. This works very well for me. 

```python
import os

rels = [
        '/etc/redhat-release',
        '/etc/fedora-release',
        '/etc/centos-release',
        '/etc/almalinux-release',
        '/etc/rocky-release'
       ]

for r in rels:
    print(f"checking {r}: result={os.path.isfile(r) and (os.path.basename(r) == os.path.basename(os.path.realpath(r)))}")
```

### Fedora 40

```python
checking /etc/redhat-release: result=False
checking /etc/fedora-release: result=True
checking /etc/centos-release: result=False
checking /etc/almalinux-release: result=False
checking /etc/rocky-release: result=False
```

### AlmaLinux 9
```python
checking /etc/redhat-release: result=False
checking /etc/fedora-release: result=False
checking /etc/centos-release: result=False
checking /etc/almalinux-release: result=True
checking /etc/rocky-release: result=False
```

### AlmaLinux 8

Note: AlmaLinux 8 has /etc/centos-release, a symlink to almalinux-release

```python
checking /etc/redhat-release: result=False
checking /etc/fedora-release: result=False
checking /etc/centos-release: result=False
checking /etc/almalinux-release: result=True
checking /etc/rocky-release: result=False
```

### Rocky Linux 9
```python
checking /etc/redhat-release: result=False
checking /etc/fedora-release: result=False
checking /etc/centos-release: result=False
checking /etc/almalinux-release: result=False
checking /etc/rocky-release: result=True
```

### CentOS Stream 9
```python
checking /etc/redhat-release: result=False
checking /etc/fedora-release: result=False
checking /etc/centos-release: result=True
checking /etc/almalinux-release: result=False
checking /etc/rocky-release: result=False
```

2024-12-12 18:33 UTC, arif-ali approved these changes

2024-12-12 18:34 UTC, arif-ali requested changes
can you squash your commits and fix the pylint/flake8 issues please

2024-12-13 00:23 UTC, metalefty commented
@arif-ali done.

2024-12-13 01:24 UTC, TurboTurtle approved these changes

2024-12-13 09:02 UTC, arif-ali approved these changes

2024-12-13 09:03 UTC, merged